In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3],[5.0,2.0,3.2]])
print(b)

[[1.  2.  3. ]
 [5.  2.  3.2]]


In [6]:
# dimension of the matrix 1D, 2D,...
print(a.ndim)
print(b.ndim)

1
2


In [7]:
# shape of the matrix 
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
# data type of the matrix
print(a.dtype)
print(b.dtype)

int32
float64


In [9]:
# number of bytes taken by matrix
print(a.nbytes)
print(b.nbytes)

12
48


In [10]:
# printing specific element
print(b[1,2])

3.2


In [11]:
# printing a full row/col
print(b[0,:])
print(b[:,1])

[1. 2. 3.]
[2. 2.]


In [12]:
# changing a number in np array
print(b)
b[0, 0] = 7
print(b)

[[1.  2.  3. ]
 [5.  2.  3.2]]
[[7.  2.  3. ]
 [5.  2.  3.2]]


In [13]:
# Zero matrix
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [14]:
# Ones matrix
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Any other matrix
np.full([2,2], 7)

array([[7, 7],
       [7, 7]])

In [16]:
#Random number matrix (b/w 0,1)
np.random.rand(5,3)

array([[0.6000945 , 0.78480378, 0.28942694],
       [0.51291539, 0.87817872, 0.84993257],
       [0.81769018, 0.34587853, 0.35695392],
       [0.97129629, 0.34070941, 0.13361595],
       [0.17012212, 0.10678441, 0.94142894]])

In [17]:
# Random number between 0 and n
np.random.randint(7, size=(3,3))

array([[6, 4, 4],
       [2, 2, 1],
       [3, 1, 4]])

In [18]:
# Random number between m and n
np.random.randint(4, 7, size=(3,3))

array([[5, 6, 5],
       [5, 6, 5],
       [4, 4, 6]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
c = np.array([3,4,5])
d = c.copy()
d[0] = 2
print(c)
print(d)

[3 4 5]
[2 4 5]


In [21]:
e = np.array([6,7,8])
print(e)

[6 7 8]


In [22]:
e - 2

array([4, 5, 6])

In [23]:
e * 2

array([12, 14, 16])

In [24]:
e / 2

array([3. , 3.5, 4. ])

In [25]:
f = np.array([4,3,2])
print(e + f)

[10 10 10]


In [26]:
np.sin(f)

array([-0.7568025 ,  0.14112001,  0.90929743])

# Linear Algebra

In [27]:
# Matrix Multiplication
g = np.ones([2,3])
print(g)

h = np.full([3,2], 2)
print(h)

# g * h wont work since it means element wise multiplication

print(np.matmul(g, h))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [28]:
# Determinant
i = np.identity(3)
print(i)

print(np.linalg.det(i))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


# Reorganizing arrays

In [29]:
# Reshaping
# Number of elements must be the same 
before = np.array([1,2,3,4,5,6])
print(before)

after = before.reshape(3,2)
print(after)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [30]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1,v2])
print(v3)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
v4 = np.hstack([v1,v2])
print(v4)

[1 2 3 4 5 6 7 8]


# Get data from a text file using Numpy


In [32]:
np.genfromtxt('data_numpy.txt', delimiter = ',')

array([[1., 2., 3., 4., 5., 4.],
       [6., 3., 3., 5., 6., 5.],
       [2., 2., 1., 1., 3., 2.]])

In [33]:
# The linspace function is especially useful if we want to create a particular number of evenly spaced values 
# in a specified half-open interval

np.linspace(6., 15., num=10)


array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [34]:
# Column-wise sum

ary = np.array([[1, 2, 3], 
                [4, 5, 6]]) # rolling over the 1st axis, axis 0

np.add.reduce(ary, axis=0)

array([5, 7, 9])

In [35]:
# Row-wise sum
np.add.reduce(ary, axis=1) # row sums

array([ 6, 15])

In [36]:
ary.sum(axis=0) # column sums

array([5, 7, 9])

In [37]:
ary.sum(axis=1) # row sums

array([ 6, 15])

In [38]:
ary.sum() # sum of entire matrix

21

In [39]:
# Addition of 1D array to a 2D array
ary2 = np.array([[4, 5, 6], 
                 [7, 8, 9]])

ary2 + ary

array([[ 5,  7,  9],
       [11, 13, 15]])

In [40]:
# Please note min/max function is also available and is same as sum we took above..

In [41]:
a = np.array([1,2,3])  # or a = [1,2,3]
b = np.array([2,3,4])  # or b = [2,3,4]
z = np.dot(a,b)
print(z)

20


In [42]:
# 2D arrays or matrices
a = [[1,2,3],[2,0,3],[7,-5,1]]
b = [[3,-1,5],[-2,-6,4], [0,4,4]]
z = np.dot(a,b)
print(z) 

[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


In [43]:
# convert lists into NumPy arrays
a = np.array(a)
b = np.array(b)
z = a.dot(b)
print(z) 

[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


In [44]:
# matrices with random integers: entries ranging from -4 to 4
a = np.random.randint(-4,4,(5,5))
b = np.random.randint(-4,4,(5,1000))
c = np.random.randint(-4,4,(1000,10))
d = np.random.randint(-4,4,(10,2000))
e = np.random.randint(-4,4,(2000,5))
# Perform multiple matrix multiplication
z = np.linalg.multi_dot([a,b,c,d,e])
print(z)

[[-14097320 -13931504 -13540660  -9566874 -14360177]
 [  9072267   9467728   8948016   6594079   9191415]
 [  3881868   3374450   2740731   1615644   4071057]
 [  6975880   7210191   7346656   5422049   6979682]
 [  5517765   5906340   6149395   4801424   5467940]]


In [45]:
# The multi_dot consumes around 9 ms compute time, whereas successive dot methods consume around 335 ms compute time to arrive at the same solution.

In [46]:
# The inner product is the scalar multiplication of one vector (or matrix) and the transpose of another vector (or matrix).
a = np.array([[1,2,3], [4,-1,0]])
b = np.array([6,3,2])
z = np.inner(a,b)
print(z) 

[18 21]


In [47]:
#Outer product is the dot product of a column vector of size M*1 and a row vector of size 1*N. The resulting array is a matrix of size M*N.

a = np.array([1,2,3,4,5])
b = np.array([6,3,2])
z = np.outer(a,b)
print(z) 

[[ 6  3  2]
 [12  6  4]
 [18  9  6]
 [24 12  8]
 [30 15 10]]


In [48]:
# Matrix Power is a general method to obtain either positive or negative powers of a given square matrix.

a = np.random.random([4,4])
# positive powers of matrix
a_2 = np.linalg.matrix_power(a, 2)
a_7 = np.linalg.matrix_power(a, 7)
# inverse of matrix
a_inv_1 = np.linalg.matrix_power(a, -1)
a_inv_3 = np.linalg.matrix_power(a, -3)
print('matrix \n', a)
print('\n matrix to the power 2\n', a_2)
print('\n matrix to the power 7\n', a_7)
print('\n matrix inverse \n', a_inv_1)
print('\n matrix cubic inverse \n', a_inv_3)

matrix 
 [[0.21191095 0.15354349 0.25750409 0.22005654]
 [0.25513765 0.65093855 0.50138904 0.07762787]
 [0.82169086 0.13242923 0.06699381 0.02005025]
 [0.40743073 0.03962974 0.36740151 0.89688699]]

 matrix to the power 2
 [[0.38532753 0.17530677 0.22965324 0.26108051]
 [0.66376017 0.53237066 0.45418301 0.18635208]
 [0.27113026 0.2220351  0.28984198 0.2104247 ]
 [0.76375985 0.17255296 0.47891626 0.90450693]]

 matrix to the power 7
 [[0.97022071 0.46641079 0.66550327 0.78729409]
 [1.54403531 0.781834   1.06540888 1.19346085]
 [0.90450305 0.44313888 0.62161844 0.72122736]
 [2.34764626 1.0856984  1.60342146 1.96932955]]

 matrix inverse 
 [[  0.7217655   -0.41281486   1.24291207  -0.16914503]
 [-11.22215143   3.93944181   0.48006132   2.40172067]
 [ 15.13607382  -3.10921562  -1.24391024  -3.41680682]
 [ -6.03237077   1.28712417  -0.0762758    2.4853469 ]]

 matrix cubic inverse 
 [[ 107.68353438  -38.82343582   29.65158212  -30.16871814]
 [-576.00046365  170.36719562  -48.77786805  145.1

In [53]:
# Eigenvalues and Eigenvectors of a matrix can be determined as follows.

a = np.random.randint(10, size=[3, 3])
Eig_val, Eig_vec = np.linalg.eig(a)
eigenvalues = np.linalg.eigvals(a)

print('Matrix: \n', a)
print('Eigen Values are: ', Eig_val)
print('Eigen Vectors are: ', Eig_vec)
print('Only Eigen Values: ', eigenvalues) 

Matrix: 
 [[6 6 6]
 [6 4 3]
 [4 6 6]]
Eigen Values are:  [15.66589819+0.j          0.16705091+0.85912107j  0.16705091-0.85912107j]
Eigen Vectors are:  [[ 0.65844086+0.j         -0.16299584+0.22284331j -0.16299584-0.22284331j]
 [ 0.48635659+0.j          0.71832303+0.j          0.71832303-0.j        ]
 [ 0.57438045+0.j         -0.59177352-0.23997781j -0.59177352+0.23997781j]]
Only Eigen Values:  [15.66589819+0.j          0.16705091+0.85912107j  0.16705091-0.85912107j]


In [54]:
# Traces of matrix are sum of diagonal elements

a = np.eye(5)
print(a)
z = np.trace(a)
print('\nTrace of matrix is: ',z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of matrix is:  5.0


In [56]:
# Solving System of Equations

# Coefficient Matrix
# a = np.random.randint(1,20,[4,4])

a = np.array([[2, -1, 3], [1, -3, -2], [3, 2, -1]])

# Dependent variable vector
#b = np.array([4,9,12,7])
b = np.array([9, 0, -1])

# solution
x = np.linalg.solve(a,b)
print('Coefficient Matrix')
print(a)
print('\nDependent Variable vector')
print(b)
print('\nSolution')
print(x) 

Coefficient Matrix
[[ 2 -1  3]
 [ 1 -3 -2]
 [ 3  2 -1]]

Dependent Variable vector
[ 9  0 -1]

Solution
[ 1. -1.  2.]
